services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Node-API 
      - PORT=3000
      - JWT_SECRET=1234782189HDKD1M2Dgdsjds
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
